# Learning how to solve systems of linear equations in python.

## Reference is https://www.youtube.com/watch?v=44pAWI7v5Zk

The system of equations is as follows:

$
\begin{align}
& 3x - 9y = -42 && 2x + 4y = 2
\end{align}
$


In [1]:
import numpy as np

In [2]:
A = np.array([[3, -9], [2, 4]]) # create a new array, and put each row of matrix A as separate elements

In [3]:
print(A)

[[ 3 -9]
 [ 2  4]]


In [4]:
b = np.array([-42, 2])

In [5]:
z = np.linalg.solve(A, b)

In [6]:
z

array([-5.,  3.])

Exercise, solve the following system of equations:

$
\begin{align}
& x - 2y - z = 6 && 2x + 2y = z + 1 &&& 2z - 1 = y + x
\end{align}
$

This is equivalent to:

$
\begin{align}
& x - 2y - z = 6 && 2x + 2y - z = 1 &&& -x - y + 2z = 1
\end{align}
$

In [7]:
A2 = np.array([[1, -2, -1], [2, 2, -1], [-1, -1, 2]]) #brackets for entire array and individual brackets for each row
print(A2)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [8]:
b2 = np.array([6, 1, 1]) #care here, if there is only one set of numbers in array for column vector then only need one set of brackets
print(b2)

[6 1 1]


In [9]:
z2 = np.linalg.solve(A2, b2)
print(z2)

[ 3. -2.  1.]
